CREATE TABLE Students (
ROLLNO TEXT PRIMARY KEY,
NAME TEXT,
ADDRESS TEXT,
PHONE TEXT,
AGE INTEGER
);

INSERT INTO Students(ROLLNO, NAME, ADDRESS, PHONE, AGE) VALUES
('1', 'JAMES', 'BEACONSFIELD', '0719362654', 15),
('2', 'THOMAS', 'HEYFORD', '0788552617', 15),
('3', 'ALFIE', 'BICESTER', '0705231196', 16),
('4', 'DEVIN', 'HEADINGTON', '0732188045', 19),
('5', 'FREDDIE', 'JERICHO', '0749981000', 17);

SELECT NAME FROM Students
WHERE NAME LIKE '%e' AND PHONE LIKE '%0';
SELECT ADDRESS FROM Students
WHERE NAME = 'JAMES' OR NAME = 'ALFIE';
SELECT NAME FROM Students
WHERE AGE < 16;
UPDATE Students
SET AGE = 17
WHERE NAME = 'DEVIN';
SELECT NAME FROM Students
WHERE AGE = 17;
SELECT NAME FROM Students
WHERE AGE = (SELECT MIN(AGE) FROM Students);
SELECT PHONE FROM Students
WHERE AGE = (SELECT MAX(AGE) FROM Students);
